#!/bin/bash

[[ $# -lt 1 ]] && exit 1
name=$(basename $1)
openssl x509 -outform der -in "$1" -out "$name.der"
keytool -import -alias your-alias -keystore "$name.jks" -file "$name.der"
mv "$name.jks" ~/Desktop
rm -rf "$name.der"

